name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Lint & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Run Terraform Format
        id: fmt
        run: |
          terraform fmt -recursive
          if [[ $(git status --porcelain) ]]; then
            echo "Terraform formatting issues detected. Fixing..."
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Auto-fix Terraform formatting"
            git push
          else
            echo "No formatting issues detected."
          fi

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Code
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_IN_AUTOMATION: true
